AuctionSystem.Web/ViewModels/CategoryViewModels.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using AuctionSystem.Entities;

namespace AuctionSystem.Web.ViewModels
{
    public class CategoryViewModel : PageViewModel
    {
        public List<Category> AllCategories { get; set; }
    }

    public class CategoryListingViewModel : PageViewModel
    {
        public List<Category> Categories { get; set; }
        public List<Auction> Auctions { get; set; }
    }

    public class CategoryDetailsViewModel : PageViewModel
    {
        public Category Category { get; set; }
    }

    public class CreateCategoryViewModel : PageViewModel
    {
        public  int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Category Category { get; set; }
        public List<Auction> Auctions { get; set; }

    }
}

AuctionSystem.Web/Controllers/AuctionController.cs
using AuctionSystem.Entities;
using AuctionSystem.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AuctionSystem.Web.ViewModels;
using Microsoft.Owin.Security.Provider;

namespace AuctionSystem.Web.Controllers
{
    public class AuctionController : Controller
    {
        AuctionServices service = new AuctionServices();
        CategoriesService categoriesService = new CategoriesService();
        // GET: Auction
        public ActionResult Index(int? categoryID,string searchTerm,int? pageNo)
        { 
            AuctionListingViewModel model = new AuctionListingViewModel();
            
            model.PageTitle = "Auction Page";
            model.PageDescription = "List of the Auctions";

            model.CategoryID = categoryID;
            model.searchTerm = searchTerm;
            model.pageNo = pageNo;

            model.Categories = categoriesService.GetAllCategories();

            return View(model);
        }
        public PartialViewResult Listing(int? categoryID, string searchTerm, int? pageNo)
        {
            var pageSize = 3;

            AuctionListingViewModel model = new AuctionListingViewModel();

            model.PageTitle = "Auction Page";
            model.PageDescription = "List of the Auctions";

            model.Auctions = service.SearchAuctions(categoryID,searchTerm,pageNo,pageSize);

            var totalAuctions = service.GetAuctionsCount(categoryID, searchTerm);

            model.Pager = new Pager(totalAuctions, pageNo, pageSize);

            return PartialView(model);

        }

        public ActionResult Create()
        {
            CreateAuctionViewModel model = new CreateAuctionViewModel();

            model.Categories = categoriesService.GetAllCategories();
            return PartialView(model);
        }

        [HttpPost]
        public JsonResult Create(CreateAuctionViewModel model)
        {
            JsonResult result = new JsonResult();

            if (ModelState.IsValid)
            {
                Auction auction = new Auction();

                auction.Title = model.Title;
                auction.Description = model.Description;
                auction.ActualAmount = model.ActualAmount;
                auction.StartingTime = model.StartingTime;
                auction.EndTime = model.EndTime;
                auction.CategoryID = model.CategoryID;

                //check AuctionPictureID Posted back from Form
                if (!string.IsNullOrEmpty(model.AuctionPictures))
                {
                    var pictureID = model.AuctionPictures.Split(',').Select(int.Parse);

                    //var pictureIds = model.AuctionPictures.Split(new char[] { ',' }, StringSplitOptions.RemoveEmptyEntries).Select(int.Parse).ToList();
                    auction.AuctionPictures = new List<AuctionPicture>();
                    auction.AuctionPictures.AddRange(pictureID
                        .Select(x => new AuctionPicture() {AuctionID = auction.ID, PictureID = x}).ToList());
                }

                service.SaveAuction(auction);

                result.Data = new {success = true};
            }
            else
            {
                result.Data = new {success = false, Error = "Invalid Inputs,Unable to Save Auction" };
            }

            return result;
        }

        public ActionResult Edit(int ID)
        {
            CreateAuctionViewModel model = new CreateAuctionViewModel();

            //var auctionservice = service.GetAuctionByID(ID);

            //model.ID = auctionservice.ID;
            //model.Title = auctionservice.Title;
            //model.Description = auctionservice.Description;
            //model.ActualAmount = auctionservice.ActualAmount;
            //model.StartingTime = auctionservice.StartingTime;
            //model.EndTime = auctionservice.EndTime;


            model.Categories = categoriesService.GetAllCategories();
            model.Auction = service.GetAuctionByID(ID);

            //model.AuctionPicturesList = auctionservice.AuctionPictures;

            
            return PartialView(model);

            
        }
        //service means AuctionService
        [HttpPost]
        public ActionResult Edit(CreateAuctionViewModel model)
        {
            //Auction auction = new Auction();

            var auction = service.GetAuctionByID(model.ID);

            //auction.ID = model.ID;

            auction.Title = model.Title;
            auction.CategoryID = model.CategoryID;
            auction.Description = model.Description;
            auction.ActualAmount = model.ActualAmount;
            auction.StartingTime = model.StartingTime;
            auction.EndTime = model.EndTime;
            

            //check AuctionPictureID Posted back from Form
            if (!string.IsNullOrEmpty(model.AuctionPictures))
            { 
                //var pictureID = model.AuctionPictures.Split(',').Select(int.Parse);

                var pictureIds = model.AuctionPictures.Split(new char[] { ',' }, StringSplitOptions.RemoveEmptyEntries).Select(int.Parse).ToList();
                auction.AuctionPictures = new List<AuctionPicture>();
                auction.AuctionPictures.AddRange(pictureIds.Select(x => new AuctionPicture() { AuctionID = auction.ID, PictureID = x }).ToList());

            }

            //AuctionID = auction.ID,
            service.UpdateAuction(auction);
            return RedirectToAction("Listing");


            
        }

        public ActionResult Delete(int ID)
        { 
            var auction = service.GetAuctionByID(ID);
            return View(auction);
        }

        [HttpPost]
        public ActionResult Delete(Auction auction)
        {
            service.DeleteAuction(auction);
            return RedirectToAction("Listing");
        }

        public ActionResult Details(int ID)
        {
            AuctionDetailsViewModel model = new AuctionDetailsViewModel();
            model.Auction = service.GetAuctionByID(ID);
            return View(model);
        }
    }
}

AuctionSystem.Web/Controllers/CategoryController.cs
using AuctionSystem.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AuctionSystem.Entities;
using AuctionSystem.Web.ViewModels;

namespace AuctionSystem.Web.Controllers
{
    public class CategoryController : Controller
    {
        CategoriesService categoriesService = new CategoriesService();
        // GET: Auction
        public ActionResult Index()
        {
            CategoryListingViewModel model = new CategoryListingViewModel();

            model.PageTitle = "Category Page";
            model.PageDescription = "List of the Categories";

            return View(model);

        }

        public ActionResult Listing()
        {
            CategoryListingViewModel model = new CategoryListingViewModel();

            model.Categories = categoriesService.GetAllCategories();

            return View(model);

        }

        public ActionResult Create()
        {
            //CreateCategoryViewModel model = new CreateCategoryViewModel();

            //model.categories = categoriesservice.getallcategories();
            
            return PartialView();
        }

        [HttpPost]
        public ActionResult Create(CreateCategoryViewModel model)
        {
            Category category = new Category();

            category.Name = model.Name;
            category.Description = model.Description;
            
            categoriesService.SaveCategory(category);
            return RedirectToAction("Listing");
        }

        public ActionResult Edit(int ID)
        {
            CreateCategoryViewModel model = new CreateCategoryViewModel();

            model.Category = categoriesService.GetCategoryByID(ID);
            
            return PartialView(model);


        }
        //service means AuctionService
        [HttpPost]
        public ActionResult Edit(CreateCategoryViewModel model)
        {
            var category = categoriesService.GetCategoryByID(model.ID);

            category.Name = model.Name;
            category.Description = model.Description;

            categoriesService.UpdateCategory(category);
            return RedirectToAction("Listing");

        }


        [HttpPost]
        public ActionResult Delete(Category category)
        {
            categoriesService.DeleteCategory(category);
            return RedirectToAction("Listing");
        }

        public ActionResult Details(int ID)
        {
            CategoryDetailsViewModel model = new CategoryDetailsViewModel();
          
            model.Category = categoriesService.GetCategoryByID(ID);

            model.PageTitle = model.Category.Name;
            model.PageDescription = model.Category.Description;

            return View(model);
        }
    }
}

AuctionSystem.Web/Views/Category/Create.cshtml
@model AuctionSystem.Web.ViewModels.CreateCategoryViewModel

<div class="modal-header">
    <h5 class="modal-title">Create Auction</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>

<form id="createForm" method="post" action="@Url.Action("Create", "Category")">

    <div class="modal-body">

        <div class="form-group">
            <label for="name">Name</label>
            <input name="Name" class="form-control" placeholder="Enter Name">
        </div>
        
        <div class="form-group">
            <label for="description">Description</label>
            <input name="Description" class="form-control" placeholder="Enter Description">
        </div>
    </div>

    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button class="btn-success" type="button" id="saveButton">Save</button>
    </div>

</form>


<script>
    $("#saveButton").click(function () {
        debugger;

        $.ajax({
                type: 'POST',
                url: '@Url.Action("Create", "Category")',
                data: $("#createForm").serialize()
            })
            .done(function(response) {

                $('#formModal').modal('toggle');
                $("#listingArea").html(response);
            });
    });
</script>

AuctionSystem.Web/Views/Category/Details.cshtml
@model AuctionSystem.Web.ViewModels.CategoryDetailsViewModel

    <div class="row">
        <div class="col-lg-12">
            <div class="col-lg-4">
                <div class="card-body">
                    <h3 class="card-title">@Model.Category.Name</h3>
                    <p class="card-text">@Model.Category.Description</p>
                </div>
            </div>

        </div>

    </div>

AuctionSystem.Web/Views/Category/Edit.cshtml
@model AuctionSystem.Web.ViewModels.CreateCategoryViewModel

<div class="modal-header">
    <h5 class="modal-title">Edit Category</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>


<form id="editForm">

    <div class="modal-body">
        <input type="hidden" name="ID" value="@Model.Category.ID" />
        <div class="form-group">
            <label>Name</label>
            <input name="Name" value="@Model.Category.Name" class="form-control" />
        </div>
         <div class="form-group">
            <label>Description</label>
            <input name="Description" value="@Model.Category.Description" class="form-control" />
        </div>
        
    </div>

    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button class="btn-success" type="button" id="updateButton">Update</button>
    </div>

</form>

<script>
    
    $("#updateButton").click(function () {
        debugger;
        
        $.ajax({
                type: 'POST',
                url: '@Url.Action("Edit", "Category")',
                data: $("#editForm").serialize()
            })
            .done(function(response) {

                $('#formModal').modal('toggle'); //to dismiss modal after finish
                $("#listingArea").html(response);
            });
    });
</script>

AuctionSystem.Web/Views/Category/Index.cshtml
<div class="row">
    <div class="col-lg-12 m-3">
        <div class="float-left">
            <h2>Categories</h2>
        </div>

        <div class="float-right">
            <!-- Create button modal -->
            <button class="btn btn-success" id="createbutton">Create New Category</button>
        </div>

        <!-- Modal -->
        <div class="modal fade" id="formModal" tabindex="-1" role="dialog" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content" id="contentArea">


                </div>
            </div>
        </div>

        <!-- Delete modal -->
        <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Confirm!</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        Are you sure you want to delete this Category?
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="button" class="btn btn-danger" id="modalDeleteBtn">Delete</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<div id="listingArea">
    @{
        Html.RenderAction("Listing");
    }
</div>

<script>
            $("#createbutton").click(function() {
                $.ajax({
                    type: 'GET',
                    url: '@Url.Action("Create", "Category")',
                }).done(function (response) {

                    $("#formModal").modal("toggle");
                    $("#contentArea").html(response);
                });
            });

            $("#modalDeleteBtn").click(function () {
                var id = $(this).attr("data-id");
                $.ajax({
                        url: '@Url.Action("Delete","Category")',
                        method: 'Post',
                        data: {
                            id: id,
                        }
                    })
                    .done(function(response) {
                        $("#deleteModal").modal('toggle');
                        $("#listingArea").html(response);
                    });
            });
</script>

AuctionSystem.Web/Views/Category/Listing.cshtml
@model AuctionSystem.Web.ViewModels.CategoryListingViewModel

<table class="table table-hover">
    <thead>
    <tr>
        <th>
            Name
        </th>
        <th>
            Description
        </th>
        <th>
            Auction
        </th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    @if (Model.Categories != null && Model.Categories.Count > 0)
    {
    foreach (var item in Model.Categories)
    {
        <tr>
            <td>@item.Name</td>
            <td>@item.Description</td>
            @if (item.Auctions != null && item.Auctions.Count > 0)
            {
                <td><a href="@Url.Action("Index", "Auction", new {CategoryID = item.ID})">@item.Auctions.Count()</a></td>
            }
            else
            {
                <td>0</td>
            }

            <td>
                <button data-id="@item.ID" class="editButton  btn btn-primary">Edit</button> |
                <button data-id="@item.ID" class="deleteButton  btn btn-danger">Delete</button>
            </td>
        </tr>
    }
    }
    </tbody>
</table>

<script>
    $(".editButton").click(function() {
        $.ajax({
            type: 'GET',
            url: '@Url.Action("Edit", "Category")',
            data: {
                ID:$(this).attr("data-id")
            }
        }).done(function (response) {

            $("#formModal").modal("toggle");
            $("#contentArea").html(response);
        });
    });

    $(".deleteButton").click(function () {

        $("#deleteModal").modal("toggle");
        $("#modalDeleteBtn").attr("data-id", $(this).attr("data-id"));
    });
</script>