AuctionSystem.Web/ViewModels/AuctionViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Routing;
using AuctionSystem.Entities;

namespace AuctionSystem.Web.ViewModels
{
    public class AuctionViewModel:PageViewModel
    { 
        public List<Auction> AllAuctions { get; set; }
        public List<Auction> FeaturedAuctions { get; set; }
    }

    public class AuctionListingViewModel : PageViewModel
    {
        public List<Auction> Auctions { get; set; }
        public Pager Pager { get; set; }
        public int? CategoryID { get; set; }
        public string searchTerm { get; set; }
        public int? pageNo { get; set; }
        public List<Category> Categories { get; set; }
    }
    public class AuctionDetailsViewModel : PageViewModel
    {
        public Auction Auction { get; set; }
    }

    public class CreateAuctionViewModel : PageViewModel
    {
        public int ID { get; set; }

        public int CategoryID { get; set; }

        [Required, MinLength(15), MaxLength(150)]
        public string Title { get; set; }
        public string Description { get; set; }

        [Range(10, 1000000)]
        public decimal ActualAmount { get; set; }
        public DateTime? StartingTime { get; set; }
        public DateTime? EndTime { get; set; }
        

        public Category Category { get; set; }
        public List<Category> Categories { get; set; }
        public string AuctionPictures { get; set; }
        public List<AuctionPicture> AuctionPicturesList { get; set; }
        public Auction Auction { get; set; }
    }
}

AuctionSystem.Web/Controllers/AuctionController.cs
using AuctionSystem.Entities;
using AuctionSystem.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AuctionSystem.Web.ViewModels;
using Microsoft.Owin.Security.Provider;

namespace AuctionSystem.Web.Controllers
{
    public class AuctionController : Controller
    {
        AuctionServices service = new AuctionServices();
        CategoriesService categoriesService = new CategoriesService();
        // GET: Auction
        public ActionResult Index(int? categoryID,string searchTerm,int? pageNo)
        { 
            AuctionListingViewModel model = new AuctionListingViewModel();
            
            model.PageTitle = "Auction Page";
            model.PageDescription = "List of the Auctions";

            model.CategoryID = categoryID;
            model.searchTerm = searchTerm;
            model.pageNo = pageNo;

            model.Categories = categoriesService.GetAllCategories();

            return View(model);
        }
        public PartialViewResult Listing(int? categoryID, string searchTerm, int? pageNo)
        {
            var pageSize = 3;

            AuctionListingViewModel model = new AuctionListingViewModel();

            model.PageTitle = "Auction Page";
            model.PageDescription = "List of the Auctions";

            model.Auctions = service.SearchAuctions(categoryID,searchTerm,pageNo,pageSize);

            var totalAuctions = service.GetAuctionsCount(categoryID, searchTerm);

            model.Pager = new Pager(totalAuctions, pageNo, pageSize);

            return PartialView(model);

        }

        public ActionResult Create()
        {
            CreateAuctionViewModel model = new CreateAuctionViewModel();

            model.Categories = categoriesService.GetAllCategories();
            return PartialView(model);
        }

        [HttpPost]
        public JsonResult Create(CreateAuctionViewModel model)
        {
            JsonResult result = new JsonResult();

            if (ModelState.IsValid)
            {
                Auction auction = new Auction();

                auction.Title = model.Title;
                auction.Description = model.Description;
                auction.ActualAmount = model.ActualAmount;
                auction.StartingTime = model.StartingTime;
                auction.EndTime = model.EndTime;
                auction.CategoryID = model.CategoryID;

                //check AuctionPictureID Posted back from Form
                if (!string.IsNullOrEmpty(model.AuctionPictures))
                {
                    var pictureID = model.AuctionPictures.Split(',').Select(int.Parse);

                    //var pictureIds = model.AuctionPictures.Split(new char[] { ',' }, StringSplitOptions.RemoveEmptyEntries).Select(int.Parse).ToList();
                    auction.AuctionPictures = new List<AuctionPicture>();
                    auction.AuctionPictures.AddRange(pictureID
                        .Select(x => new AuctionPicture() {AuctionID = auction.ID, PictureID = x}).ToList());
                }

                service.SaveAuction(auction);

                result.Data = new {success = true};
            }
            else
            {
                result.Data = new {success = false, Error = "Invalid Inputs,Unable to Save Auction" };
            }

            return result;
        }

        public ActionResult Edit(int ID)
        {
            CreateAuctionViewModel model = new CreateAuctionViewModel();

            //var auctionservice = service.GetAuctionByID(ID);

            //model.ID = auctionservice.ID;
            //model.Title = auctionservice.Title;
            //model.Description = auctionservice.Description;
            //model.ActualAmount = auctionservice.ActualAmount;
            //model.StartingTime = auctionservice.StartingTime;
            //model.EndTime = auctionservice.EndTime;


            model.Categories = categoriesService.GetAllCategories();
            model.Auction = service.GetAuctionByID(ID);

            //model.AuctionPicturesList = auctionservice.AuctionPictures;

            
            return PartialView(model);

            
        }
        //service means AuctionService
        [HttpPost]
        public ActionResult Edit(CreateAuctionViewModel model)
        {
            //Auction auction = new Auction();

            var auction = service.GetAuctionByID(model.ID);

            //auction.ID = model.ID;

            auction.Title = model.Title;
            auction.CategoryID = model.CategoryID;
            auction.Description = model.Description;
            auction.ActualAmount = model.ActualAmount;
            auction.StartingTime = model.StartingTime;
            auction.EndTime = model.EndTime;
            

            //check AuctionPictureID Posted back from Form
            if (!string.IsNullOrEmpty(model.AuctionPictures))
            { 
                //var pictureID = model.AuctionPictures.Split(',').Select(int.Parse);

                var pictureIds = model.AuctionPictures.Split(new char[] { ',' }, StringSplitOptions.RemoveEmptyEntries).Select(int.Parse).ToList();
                auction.AuctionPictures = new List<AuctionPicture>();
                auction.AuctionPictures.AddRange(pictureIds.Select(x => new AuctionPicture() { AuctionID = auction.ID, PictureID = x }).ToList());

            }

            //AuctionID = auction.ID,
            service.UpdateAuction(auction);
            return RedirectToAction("Listing");


            
        }

        public ActionResult Delete(int ID)
        { 
            var auction = service.GetAuctionByID(ID);
            return View(auction);
        }

        [HttpPost]
        public ActionResult Delete(Auction auction)
        {
            service.DeleteAuction(auction);
            return RedirectToAction("Listing");
        }

        public ActionResult Details(int ID)
        {
            AuctionDetailsViewModel model = new AuctionDetailsViewModel();
            model.Auction = service.GetAuctionByID(ID);
            return View(model);
        }
    }
}

AuctionSystem.Web/Controllers/SharedController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AuctionSystem.Entities;
using AuctionSystem.Services;

namespace AuctionSystem.Web.Controllers
{
    public class SharedController : Controller
    {
        SharedService service = new SharedService();

        [HttpPost]
        public JsonResult UploadPictures()
        {
            JsonResult result = new JsonResult();
            List<object> picturesJSON = new List<object>();

            var pictures = Request.Files;

            for (int i = 0; i < pictures.Count; i++)
            {
                var picture = pictures[i];
                var fileName = Guid.NewGuid() + Path.GetExtension(picture.FileName);

                //create picName, and path(url)
                var path = Server.MapPath("~/Content/images/") + fileName;

                //var picUrl = "~/Content/images/" + fileName;

                // upload pic into images file
                picture.SaveAs(path);

                var dbPicture = new Picture(); //OBject of Picture Entity
                dbPicture.URL = fileName;

                int pictureID = service.SavePicture(dbPicture);

                picturesJSON.Add(new {ID = pictureID,URL = fileName});
            }
            //pictureURL = path
            result.Data = picturesJSON;

            return result ;
        }
    }
}

AuctionSystem.Web/Views/Auction/Create.cshtml
@model AuctionSystem.Web.ViewModels.CreateAuctionViewModel

<div class="modal-header">
    <h5 class="modal-title">Create Auction</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>

<form id="createForm" method="post" action="@Url.Action("Create", "Auction")">    
    
    <div class="modal-body">

        <div class="form-group">
            <label for="title">Title</label>
            <input name="Title" class="form-control" placeholder="Enter Title" value="@Model.Title">
        </div>
        <div class="form-group">
            <label>Category</label>
            <select class="form-control" name="CategoryID">
                @foreach (var category in Model.Categories)
                {
                    <option value="@category.ID">@category.Name</option>
                }
            </select>
        </div>
        <div class="form-group">
            <label for="description">Description</label>
            <input name="Description" class="form-control" placeholder="Enter Description" value="@Model.Description">
        </div>
        <div class="form-group">
            <label for="amount">Actual Amount</label>
            <input name="ActualAmount" class="form-control" placeholder="Enter Amount" value="@Model.ActualAmount">
        </div>
        <div class="form-group">
            <label>Starting Time</label>
        </div>
        <div class="form-group">
            <label>Ending Time</label>
            <input name="EndTime" class="form-control"  value="@Model.StartingTime"/>
        </div>
        
        <div class="form-group">
            <label>Select Pictures</label>
            <input id="auctionPictures" class="form-control" name="AuctionPictures" type="file" multiple />
            <div id="picsArea">

            </div>
            
            <input type="hidden" name="AuctionPictures" id="pictureIDs" />
        </div>
        
        <div id="formErrors" class="form-group bg-danger "  style="display: none">

        </div>
        
    </div>
   
    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button class="btn-success" type="button" id="saveButton">Save</button>
    </div>

</form>


<script>

    $("#createform").validate({
        rules: {
            title: {
                required:true,
                minlength:15,
                maxlength:150
            },
            actualamount: {
                required: true,
                range: [10, 1000000]
            }
        },
            messages: {
                title: {
                    required:"title is required",
                    minlength:"minlength is 15",
                    maxlength:"maxlength is 150"
                
            },
                actualamount: {
                    required: "actual amount is required",
                    range: "invalid range"
                    }
            },
        
    })

    $("#saveButton").click(function() {
        debugger;

        if ($("#createForm").valid()) {
            var imageIDs = [];

            $("#picsArea .image").each(function() {

                var imageID = $(this).attr("data-id");
                imageIDs.push(imageID);
            })

            $("#pictureIDs").val(imageIDs);

            $.ajax({
                    type: 'POST',
                    url: '@Url.Action("Create", "Auction")',
                    data: $("#createForm").serialize()
                })
                .done(function (response) {
                    debugger; 
                    if (response.success) {
                        ReloadListing();
                        $('#formModal').modal('toggle');
                    
                    }
                    else {
                        $("#formErrors").html(response.Error);
                        $("#formErrors").show();
                    }

                });
        }
    });

    $("#auctionPictures").change(function() {
        var pictures = this.files;
        var picsData = new FormData();

        for (var i = 0; i < pictures.length; i++) {
            picsData.append("Picture", pictures[i]);
        }

        $.ajax({
                type: 'POST',
                url: '@Url.Action("UploadPictures", "Shared")',
                data: picsData,
                dataType: 'json',
                processData: false,
                contentType: false
            })
            .done(function(responses) {

                for (var i = 0; i < responses.length; i++) {
                    var picResponse = responses[i];

                    AttachNewImage(picResponse.ID,picResponse.URL);
                }
            });
    });


</script>

AuctionSystem.Web/Views/Auction/Delete.cshtml
@model AuctionSystem.Entities.Auction

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Auction</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        @*<dt>
            @Html.DisplayNameFor(model => model.ImageURL)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImageURL)
        </dd>*@

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ActualAmount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ActualAmount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartingTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartingTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndTime)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

<div class="form-actions no-color">
    <input type="submit" value="Yes" class="btn btn-default" />
    <input type="button" value="No" class="btn btn-default" onclick="location.href = '@Url.Action("Index", "Auction")'" />
    @*@Html.ActionLink("Back to List", "Index")*@
</div>
    }
</div>

AuctionSystem.Web/Views/Auction/Edit.cshtml
@model AuctionSystem.Web.ViewModels.CreateAuctionViewModel

<div class="modal-header">
    <h5 class="modal-title">Edit Auction</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>


<form id="editForm" >

    <div class="modal-body">
        <input type="hidden" name="ID" value="@Model.Auction.ID" />
        <div class="form-group">
            <label>Title</label>
            <input name="Title" value="@Model.Auction.Title" class="form-control" />
        </div>
        <div class="form-group">
            <label for="Category">Category</label>
            <select class="form-control" name="CategoryID">
                @foreach (var category in Model.Categories)
                {
                    var selected = category.ID == Model.Auction.CategoryID ? "selected" : string.Empty;
                    //var selected = category.ID == Model.Auction.CategoryID ? "selected" : string.Empty;
                    <option @selected value="@category.ID" >@category.Name</option>
                }
            </select>
        </div>
        <div class="form-group">
            <label>Description</label>
            <input name="Description" value="@Model.Auction.Description" class="form-control" />
        </div>
        <div class="form-group">
            <label>Actual Amount</label>
            <input name="ActualAmount" value="@Model.Auction.ActualAmount" class="form-control" />
        </div>
        <div class="form-group">
            <label>Starting Time</label>
            <input name="StartingTime" value="@Model.Auction.StartingTime" class="form-control" />
        </div>
        <div class="form-group">
            <label>Ending Time</label>
            <input name="EndTime" value="@Model.Auction.EndTime" class="form-control" />
        </div>

        <div class="form-group">
            <label>Select Pictures</label>
            <input id="auctionPictures" class="form-control" name="AuctionPictures" type="file" multiple />
            <input type="hidden" name="AuctionPictures" id="pictureIDs" />
            <div id="picsArea" class="mt-2">
                @if (Model.Auction.AuctionPictures != null && Model.Auction.AuctionPictures.Count > 0)
                {
                    foreach (var picture in Model.Auction.AuctionPictures)
                    {
                        <img src='/Content/images/@picture.Picture.URL' class='image img-thumbnail'  data-id="@picture.PictureID" style="width: 200px; height: 200px;" />
                    }
                }

            </div>
            
        </div>

    </div>

    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button class="btn-success" type="button" id="updateButton">Update</button>
    </div>

</form>

<script>
    RemoveImageOnClick();

    $("#updateButton").click(function () {
        debugger;
        var imageIDs = [];

        $("#picsArea .image").each(function () {

            
            var imageID = $(this).attr("data-id");
            imageIDs.push(imageID);
        })

        $("#pictureIDs").val(imageIDs);

        $.ajax({
                type: 'POST',
                url: '@Url.Action("Edit", "Auction")',
                data: $("#editForm").serialize()
            })
            .done(function(response) {

                $('#formModal').modal('toggle'); //to dismiss modal after finish
                $("#listingArea").html(response);
            });
    });

    $("#auctionPictures").change(function() {
        var pictures = this.files;
        var picsData = new FormData();

        for (var i = 0; i < pictures.length; i++) {
            picsData.append("Picture", pictures[i]);
        }

        $.ajax({
                type: 'POST',
                url: '@Url.Action("UploadPictures", "Shared")',
                data: picsData,
                dataType: 'json',
                processData: false,
                contentType: false
            })
            .done(function(responses) {

                for (var i = 0; i < responses.length; i++) {
                    var picResponse = responses[i];

                    AttachNewImage(picResponse.ID,picResponse.URL);
                }
            });
    });
</script>

AuctionSystem.Web/Views/Auction/Index.cshtml
@model AuctionSystem.Web.ViewModels.AuctionListingViewModel

@{
    var categoryID = Model.CategoryID.HasValue ? Model.CategoryID.Value : 0;
}

<div class="row">
    <div class="col-lg-12 m-3">
        <div class="float-left">
            <h2>Auctions</h2>
        </div>
    </div>
</div>

<div class="row mb-3">
    <div class="col col-lg-12">
        <form method="post">
            <div class="input-group">
                @if (Model.Categories != null && Model.Categories.Count > 0)
                {
                    <select class="form-control mr-1" name="categoryID">
                        <option>
                            Select Category
                        </option>
                        @foreach (var category in Model.Categories)
                        {
                            var selected = category.ID == categoryID ? "selected" : string.Empty;
                            <option value="@category.ID" @selected> @category.Name </option>
                        }
                    </select>
                }

                <input type="text" id="searchTxt" name="SearchTerm" class="form-control mr-1" placeholder="Search" value="@Model.searchTerm">

                <div class="input-group-append" id="button-addon4">

                    <button id="searchBtn" class="btn btn-outline-primary mr-1" type="submit">Search</button>

                    @*<a href="@Url.Action("Index","Auction")" class="btn btn-outline-secondary mr-1">Reset</a>

                        <button class="action-btn btn btn-outline-success" id="createBtn" type="button">New</button>*@
                </div>
            </div>
        </form>
    </div>

    <div id="listingArea">
        @{
            Html.RenderAction("Listing",new { categoryID = Model.CategoryID, SearchTerm = Model.searchTerm, PageNo = Model.pageNo});
        }
    </div>

    <div class="float-right">
        <!-- Create button modal -->
        <button class="btn btn-success" id="createbutton">Create new auction</button>
    </div>



    <!-- Modal -->
    <div class="modal fade" id="formModal" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content" id="contentArea">


            </div>
        </div>
    </div>

    <!-- Delete modal -->
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Confirm!</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    Are you sure you want to delete this auction?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-danger" id="modalDeleteBtn">Delete</button>
                </div>
            </div>
        </div>
    </div>
</div>


<div id="imageTemplate" style="display: none">
    <img class='image img-thumbnail' style="width: 200px; height: 200px;" src="" data-id="" />
</div>


@*<script src="https://cdn.jsdelivr.net/npm/jquery-validation@1.19.3/dist/jquery.validate.min.js"></script>*@
    
<script>
            $("#createbutton").click(function() {
                $.ajax({
                    type: 'GET',
                    url: '@Url.Action("Create", "Auction")',
                }).done(function (response) {

                    $("#formModal").modal("toggle");
                    $("#contentArea").html(response);
                });
            });

            $("#modalDeleteBtn").click(function () {
                var id = $(this).attr("data-id");
                $.ajax({
                        url: '@Url.Action("Delete","Auction")',
                        method: 'Post',
                        data: {
                            id: id,
                        }
                    })
                    .done(function(response) {
                        $("#deleteModal").modal('toggle');
                        $("#listingArea").html(response);
                    });
            });

            $("#searchBtn").click(function () {
                var searchValue = $("#searchTxt").val();

                $.ajax({
                    url: '@Url.Action("Listing", "Auction")',
                    data: {
                        categoryId: $("#categoryID").val(),
                        search: searchValue
                        }
                    })
                    .done(function (response) {
                        $("#listingArea").html(response);
                    })
                    .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                        alert("FAIL");
                    });
            });

            //clone image template html to every added image
            function AttachNewImage(imageID,imageURL) {
                var imgHtml = $("#imageTemplate").clone();

                imgHtml.find(".image").attr('data-id',imageID);
                imgHtml.find(".image").attr("src", "/Content/images/" + imageURL);


                $("#picsArea").append(imgHtml.html());

                RemoveImageOnClick();
            }

            function RemoveImageOnClick() {
                $("#picsArea .image").click(function() {
                    debugger;

                    $(this).remove();

                });
    }

            function ReloadListing() {
                $.ajax({
                        url: '@Url.Action("Listing", "Auction")',
                        type: 'GET',
                    })
                    .done(function(response) {
                        $("#listingArea").html(response);
                    });
            }

</script>

AuctionSystem.Web/Views/Auction/Listing.cshtml
@model AuctionSystem.Web.ViewModels.AuctionListingViewModel

<table class="table table-hover">
    <tr>
        <th>
            Title
        </th>
        <th>
            Category
        </th>
        <th>
            Description
        </th>
        <th>
            ActualAmount
        </th>
        <th>
            StartingTime
        </th>
        <th>
            EndTime
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model.Auctions)
    {
        <tr>
            <td>@item.Title</td>
            <td>@item.Category.Name</td>
            <td>@item.Description</td>
            <td>@item.ActualAmount</td>
            <td>@item.StartingTime</td>
            <td>@item.EndTime</td>

            <td>
                <button data-id="@item.ID" class="editButton  btn btn-primary">Edit</button> |
                <button data-id="@item.ID" class="deleteButton  btn btn-danger">Delete</button>
            </td>

        </tr>
    }

</table>

@if (Model.Pager != null && Model.Pager.TotalPages > 0)
{
    <nav aria-label="Page navigation example">
        
        <ul class="pagination justify-content-center">
    @if (Model.Pager.CurrentPage == 1)
    {
    <li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
    }
    else
    {
    <li class="page-item">
        <a class="page-link" href="@Url.Action("Index", "Auction",
                                       new {pageNo = Model.Pager.CurrentPage - 1, 
                                           categoryID = Model.CategoryID, SearchTerm = Model.searchTerm})">Previous
        </a>
    </li>
    }

    @for (int page = Model.Pager.StartPage; page < Model.Pager.EndPage; page++)
    {
        var active = page == Model.Pager.CurrentPage ? "active" : string.Empty;
        
        <li class="page-item @active"><a class="page-link" href="@Url.Action("Index", "Auction", new {pageNo = page, categoryID = Model.CategoryID, SearchTerm = Model.searchTerm})">
            @page
        </a>
        </li>
        
    }
    @if (Model.Pager.CurrentPage == Model.Pager.EndPage) 
    {
        <li class="page-item disabled"><a class="page-link" href="#">Next</a></li>
    }
    else
    {
        <li class="page-item"><a class="page-link" href="@Url.Action("Index", "Auction",
                                                             new { pageNo = Model.Pager.CurrentPage + 1,categoryID = Model.CategoryID,SearchTerm = Model.searchTerm})">Next</a></li>
    }
        </ul>
        </nav>
    }


<script>
    $(".editButton").click(function() {
        $.ajax({
            type: 'GET',
            url: '@Url.Action("Edit", "Auction")',
            data: {
                ID:$(this).attr("data-id")
            }
        }).done(function (response) {

            $("#formModal").modal("toggle");
            $("#contentArea").html(response);
        });
    });

    $(".deleteButton").click(function () {

        $("#deleteModal").modal("toggle");
        $("#modalDeleteBtn").attr("data-id", $(this).attr("data-id"));
    });
</script>